### ISSUE TITLE
Portal visual recursion

### ISSUE THREAD

**Issue by Detalderus** [aurycat/UdonPortals#1]
Hello. Can you add visual recursion of portals? So that the contents of the second portal can be seen through the first portal. Like in this video: https://www.youtube.com/watch?v=cWpFZbjtSQg&t=811s
This is necessary to create a looping world.

**Comment by aurycat** [comment]
Doing recursion correctly within the limits of VRChat is really hard. It's not impossible, but I don't have plans to implement it right now, sorry.

One way to fake a looping world with the portals, without real visual recursion, is to have the portals not render at all on the 2nd iteration, and then have actual geometry behind the portal that is a copy of whatever would be on the opposite side. So like

[object A]  [portal ->]  [room]  [<- portal] [another real copy of object A]

if that makes sense. It won't always work well, just depends on how the room is setup. It would basically be like only using the portals in "physics only" mode, except you still render the players up to 1 level deep as they walk through the portals.

You'll have to modify the code to completely not render the portals when doing a render. The best way I can think of off the top of my head is to disable the partner portal's mesh renderer right before the call to Render() on the cameras, in OnWillRenderObject, and then turn it back on immediately after.

**Comment by Detalderus** [comment]
thanks, I'll try.
